language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - apt-cache search boost
    - apt-cache search eigen
    - sudo apt-get install libboost1.54-all-dev
    - sudo apt-get install libeigen3-dev
script: cmake . -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
