language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo echo "deb http://archive.ubuntu.com/ubuntu precise unstable" >> /etc/apt/sources.list
    - sudo echo "deb-src http://archive.ubuntu.com/ubuntu precise unstable" >> /etc/apt/sources.list
    - cat /etc/apt/sources.list 
    - sudo apt-get update
    - apt-cache show libboost-dev
    - apt-cache show libeigen3-dev
    - sudo apt-get -t unstable install libboost-dev
    - sudo apt-get -t unstable install libeigen3-dev
    - mkdir ../build
    - cd ../build
script: cmake ../gp -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
