language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository -y ppa:kalakris/eigen
    - sudo add-apt-repository -y ppa:mapnik/boost
    - sudo apt-get update
    - sudo apt-get install libboost-dev
    - sudo apt-get install libeigen3-dev
    - mkdir ../build
    - cd ../build
script: cmake ../gp -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
