language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository ppa:kalakris/eigen
    - sudo add-apt-repository ppa:mapnik/boost
    - sudo apt-get update
    - apt-cache show libboost-dev
    - apt-cache show libeigen3-dev
    - sudo apt-get -t unstable install libboost-dev
    - sudo apt-get -t unstable install libeigen3-dev
    - mkdir ../build
    - cd ../build
script: cmake ../gp -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
