language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - ls
    - pwd
    - sudo apt-get update
    - apt-cache show libboost-dev
    - apt-cache show libeigen3-dev
    - sudo apt-get install libboost-dev
    - sudo apt-get install libeigen3-dev
    - mkdir ../build
    - cd ../build
script: cmake ../gp -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
