language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository -y ppa:liggghts-dev/external
    - sudo add-apt-repository -y ppa:mapnik/boost
    - sudo add-apt-repository -y ppa:lopeztobal/maths
    - sudo apt-get update
    - sudo apt-get install libeigen3-dev
    - sudo apt-get install libboost1.49-dev
    - sudo apt-get install gsl
    - mkdir ../build
    - cd ../build
script: cmake ../gp -DCMAKE_BUILD_TYPE=Release && make && make test
branches:
    only:
        - master
        - develop
